# Generated by Django 5.0.4 on 2024-04-24 15:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_product_category_alter_product_price_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imgUrl',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='imgUrl',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
